name: Publish Webcal

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download ICS from shared drive
        run: |
          curl -L -o webcal.ics "https://www.dropbox.com/scl/fi/aaqsjmarl2i1cy7ebqjzk/webcal.ics?rlkey=1c3bpm3ohi5v269v0gsrje8kq&dl=1"

      - name: Commit and push if changed
        run: |
          git config user.name "Webcal Bot"
          git config user.email "webcal@yourdept.ca"
          git add webcal.ics
          git commit -m "Auto-update webcal" || exit 0
          git push
